### ISSUE TITLE
IsEmbed error

### ISSUE THREAD

**Issue by ghost** [akshatmittal/youtube-realtime#20]
Hello, my browser getting error on source code of your website: 

> jquery.min.js:2 jQuery.Deferred exception: isEmbed is not defined ReferenceError: isEmbed is not defined
    at Object.prepare (/assets/js/script.js:4:61)
    at HTMLDocument.<anonymous> (assets/js/script.js:11:352)
    at j (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.0/jquery.min.js:2:29999)
    at k (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.0/jquery.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught ReferenceError: isEmbed is not defined
    at Object.prepare (script.js:4)
    at HTMLDocument.<anonymous> (script.js:11)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)

**Comment by akshatmittal** [comment]
Hey I just verified the working and the code for the embeds and they seem to be working fine. You should not see that error in any standard embed. 

You might see this error (right before being redirected to the main website) if you open the embeds URL without the embed tag, which should not be done.
